complexity:
  LongParameterList:
    ignoreDefaultParameters: true
  LongMethod:
    threshold: 1000

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Za-z0-9]*'
